---
- name: Obtain vm information
  setup:
  vars:
    ansible_host: "{{ vm_ip }}"
    warn: no

- name: Hostname Configuration
  command: hostnamectl set-hostname "{{ inventory_hostname }}"
  vars:
    ansible_host: "{{ vm_ip }}"
...