---
- name: Obtiene la información de la mv
  setup:
  vars:
    ansible_host: "{{ vm_ip }}"

- name: Hostname Configuration
  command: hostnamectl set-hostname "{{ inventory_hostname }}"
  vars:
    ansible_host: "{{ vm_ip }}"
...