---
- name: Define a patch for ingress
  copy:
    dest: "{{ ansible_env.HOME }}/{{service}}.ingress.patch.yml"
    content: |
      spec:
        rules:
        - host: {{service}}.{{ network_name }}.local
          http:
            paths:
            - path: {{ route }}
              backend:
                serviceName: {{ service }}
                servicePort: {{ externalport }}

- name: Apply Patch
  shell: kubectl patch ingress --type='merge' -n kube-system traefik -p "$(cat {{ ansible_env.HOME }}/{{service}}.ingress.patch.yml)"
...
