---
- name: Install Traefik helm
  when: container_engine != "k3s" or network_controller is defined
  vars:
    namespace: "kube-system"
    service: "traefik"
    file: "stable/traefik"
    setYaml: |
      dashboard:
        enabled: "true"
        domain: "traefik-dashboard.{{ domain }}"
        auth:
          basic:
            test: '$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/'
      rbac:
        enabled: "true"
      ssl:
        enabled: "true"
        optional: "true"
        mtls:
          enabled: "true"
        generateTLS: "true"
      metrics:
        prometheus:
          enabled: "true"
  include_role:
    name: addons
    tasks_from: helm

- name: Wait to raise Traefik
  when: container_engine == "k3s" and network_controller is not defined
  shell: kubectl get pods -n kube-system |grep traefik|grep -v helm|grep Running
  register: traefik_state
  retries: 25
  delay: 10
  until: traefik_state.stdout != ""

- name: Define a patch for traefik configmap
  when: container_engine != "k3s" or network_controller is defined
  copy:
    dest: "{{ ansible_env.HOME }}/traefik.cm.patch.yml"
    content: |
      data:
        traefik.toml: |
          # traefik.toml
          logLevel = "info"
          defaultEntryPoints = ["http","https","traefik"]
          [entryPoints]
            [entryPoints.http]
            address = ":80"
            compress = true
            [entryPoints.https]
            address = ":443"
            compress = true
              [entryPoints.https.tls]
                [entryPoints.https.tls.ClientCA]
                files = []
                optional = true
                [[entryPoints.https.tls.certificates]]
                CertFile = "/ssl/tls.crt"
                KeyFile = "/ssl/tls.key"
            [entryPoints.traefik]
              address = ":8080"
              [entryPoints.traefik.auth.basic]
              users = ["admin:$apr1$zjjGWKW4$W2JIcu4m26WzOzzESDF0W/"]
          [ping]
          entryPoint = "http"
          [kubernetes]
            [kubernetes.ingressEndpoint]
            publishedService = "kube-system/traefik"
          [traefikLog]
            format = "json"
          [api]
            entryPoint = "traefik"
            dashboard = true
          [metrics]
            [metrics.prometheus]
              entryPoint = "traefik"

- name: Define a patch for traefik configmap
  when: container_engine == "k3s" and network_controller is not defined
  copy:
    dest: "{{ ansible_env.HOME }}/traefik.cm.patch.yml"
    content: |
      data:
        traefik.toml: |
          # traefik.toml
          logLevel = "INFO"
          defaultEntryPoints = ["http","https","traefik"]
          [entryPoints]
            [entryPoints.http]
            address = ":80"
            compress = true
            [entryPoints.https]
            address = ":443"
            compress = true
              [entryPoints.https.tls]
                [[entryPoints.https.tls.certificates]]
                CertFile = "/ssl/tls.crt"
                KeyFile = "/ssl/tls.key"
            [entryPoints.traefik]
              address = ":8080"
              [entryPoints.traefik.auth.basic]
              users = ["admin:$apr1$zjjGWKW4$W2JIcu4m26WzOzzESDF0W/"]
          [ping]
          entryPoint = "http"
          [kubernetes]
            [kubernetes.ingressEndpoint]
            publishedService = "kube-system/traefik"
          [traefikLog]
            format = "json"
          [api]
          entryPoint = "traefik"
            dashboard = true
          [metrics]
            [metrics.prometheus]
              entryPoint = "traefik"

- name: Define a patch for traefik deployment
  copy:
    dest: "{{ ansible_env.HOME }}/traefik.deploy.patch.yml"
    content: |
      spec:
        template:
          spec:
            containers:
            - args:
              - --configfile=/config/traefik.toml
              image: traefik:1.7.9
              name: traefik
              ports:
              - containerPort: 8080
                name: dashboard
                protocol: TCP

- name: Define a patch for traefik service
  when: container_engine == "k3s" and network_controller is not defined
  copy:
    dest: "{{ ansible_env.HOME }}/traefik.svc.patch.yml"
    content: |
      spec:
        ports:
        - name: dashboard
          port: 8080
          protocol: TCP
          targetPort: dashboard

- name: Configure traefik deployment
  when: container_engine == "k3s" and network_controller is not defined
  shell: kubectl patch deployment -n kube-system traefik -p "$(cat {{ ansible_env.HOME }}/traefik.deploy.patch.yml)"

- name: Configure traefik configmap
  when: container_engine == "k3s" and network_controller is not defined
  shell: kubectl patch configmap -n kube-system traefik -p "$(cat {{ ansible_env.HOME }}/traefik.cm.patch.yml)"

- name: Configure traefik service
  when: container_engine == "k3s" and network_controller is not defined
  shell: kubectl patch service -n kube-system traefik -p "$(cat {{ ansible_env.HOME }}/traefik.svc.patch.yml)"

- name: Reload traefik configuration
  when: container_engine == "k3s" and network_controller is not defined
  shell: kubectl -n kube-system delete pod `kubectl -n kube-system get pods |grep ^traefik|awk '{print $1}'`

- include: traefik_add_route.yml
  vars:
    service: traefik
    route: "/"
    internalport: 8080
    namespace: kube-system
...
