---
- name: create GW
  ec2_vpc_igw:
   vpc_id: "{{ vpc_id }}"
   region: "{{ region }}"
   aws_access_key: "{{ aws_access_key }}"
   aws_secret_key: "{{ aws_secret_key }}"
   state: "{{ state }}"
   tags:
     Name: '{{ name_encoded }}'
  register: igw
  vars:
    name_encoded: '{{ [dn,name] | join("_") | regex_replace ("\W","_") }}'

- set_fact:
    cacheable: yes
    '{{ [dn,name] | join("_") | regex_replace ("\W","_") }}_igw_id': "{{ igw.gateway_id | default(omit) }}"
    igw_id: '{{ igw.gateway_id | default(omit) }}'
