---
- name: Add kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present

- sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    sysctl_set: yes
    state: present

- name: Update repositories cache and install dirmngr and curl packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - software-properties-common
    - dirmngr
    - conntrack
    - ipvsadm
  when: ansible_os_family == "Debian"

- name: Update repositories cache and install kubernetes dependences
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - conntrack-tools
    - ipvsadm
  when: ansible_os_family == "Redhat"

- name: Creates directory cni
  file:
    path: /opt/cni/bin
    state: directory

- name: Check that the Containerd binary exists
  stat:
    path: /usr/local/bin/containerd
  register: containerd_stat_result

- name: Install last CNI version
  when: containerd_stat_result.stat.exists == false
  shell: curl -LSs https://storage.googleapis.com/cri-containerd-release/cri-containerd-cni-1.2.7.linux-amd64.tar.gz |tar --no-overwrite-dir -C / -xz
  args:
    warn: no

- name: Check that the kubelet binary exists
  stat:
    path: /usr/bin/kubelet
  register: kubelet_stat_result

- name: Check that the kubeadm binary exists
  stat:
    path: /usr/bin/kubeadm
  register: kubeadm_stat_result

- name: Obtain the last kubernetes version
  shell: curl -sSL https://dl.k8s.io/release/stable.txt
  register: kubernetes_version
  run_once: true
  args:
    warn: no

- name: install Kubelet and kubectl
  when: kubelet_stat_result.stat.exists == false
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kubernetes_version.stdout }}/bin/linux/amd64/{{ item }}
    dest: /usr/bin/{{ item }}
    mode: '0755'
    username: root
    group: root
  with_items:
    - kubelet
    - kubectl

- name: obtiene el nombre del master
  command: echo "{{ inventory_hostname }}"
  register: master_name
  run_once: true
  when: master_name is not defined

- name: install Kubeadm in master
  run_once: true
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kubernetes_version.stdout }}/bin/linux/amd64/kubeadm
    dest: /usr/bin/kubeadm
    mode: '0755'
    username: root
    group: root
  when: kubeadm_stat_result.stat.exists == false and master_name is defined and master_name.stdout == inventory_hostname

- name: Check that the kubelet service exists
  stat:
    path: /etc/systemd/system/kubelet.service
  register: kubelet_service_stat

- name: install /etc/systemd/system/kubelet.service
  when: kubelet_service_stat.stat.exists == false and master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  copy:
    dest: /etc/systemd/system/kubelet.service
    content: |
      [Unit]
      Description=kubelet: The Kubernetes Node Agent
      Documentation=http://kubernetes.io/docs/
      
      [Service]
      # This is a file that "kubeadm init" and "kubeadm join" generates at runtime, populating the KUBELET_KUBEADM_ARGS variable dynamically
      EnvironmentFile=-/var/lib/kubelet/kubeadm-flags.env
      EnvironmentFile=-/etc/default/kubelet
      ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS
      Restart=always
      StartLimitInterval=0
      RestartSec=10
      
      [Install]
      WantedBy=multi-user.target

- name: install /etc/systemd/system/kubelet.service
  when: kubelet_service_stat.stat.exists == false and master_name is defined and master_name.stdout != inventory_hostname
  copy:
    dest: /etc/systemd/system/kubelet.service
    content: |
      [Unit]
      Description=kubelet: The Kubernetes Node Agent
      Documentation=http://kubernetes.io/docs/
      
      [Service]
      EnvironmentFile=-/etc/default/kubelet
      ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_EXTRA_ARGS
      Restart=always
      StartLimitInterval=0
      RestartSec=10
      
      [Install]
      WantedBy=multi-user.target

- name: install /etc/default/kubelet
  when: master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  copy:
    dest: /etc/default/kubelet
    content: |
      KUBELET_EXTRA_ARGS='--network-plugin=cni --container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock --node-ip={{ vm_ip }}'
      KUBELET_KUBECONFIG_ARGS='--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf'
      KUBELET_CONFIG_ARGS='--config=/var/lib/kubelet/config.yaml'

- name: install /etc/default/kubelet
  when: master_name is defined and master_name.stdout != inventory_hostname
  copy:
    dest: /etc/default/kubelet
    content: |
      KUBELET_EXTRA_ARGS='--network-plugin=cni --container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock --node-ip={{ vm_ip }}'
      KUBELET_KUBECONFIG_ARGS='--bootstrap-kubeconfig=/var/lib/kubelet/bootstrap-kubeconfig --kubeconfig=/var/lib/kubelet/kubeconfig'
      KUBELET_CONFIG_ARGS=''

- name: enable and start containerd service
  systemd:
    name: containerd
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started

- name: Check that kubeadm was executed
  when: master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  stat:
    path: "{{ ansible_env.HOME }}/.kubeadm"
  register: kubeadmex_stat_result

- name: execute kubeadm
  shell: kubeadm init --service-dns-domain {{ domain }}--apiserver-advertise-address {{ vm_ip }} --pod-network-cidr=10.244.0.0/16 --cri-socket /run/containerd/containerd.sock  | grep "kubeadm join"|grep token
  register: secret_token
  run_once: true
  when: kubeadmex_stat_result.stat.exists == false and master_name is defined and master_name.stdout == inventory_hostname

- name: Schedule master node
  when: kubeadmex_stat_result.stat.exists == false and master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  shell: "{{ item }}"
  with_items:
    - mkdir  {{ ansible_env.HOME }}/.kube
    - cp -i /etc/kubernetes/admin.conf {{ ansible_env.HOME }}/.kube/config
    - kubectl taint nodes {{ inventory_hostname }} node-role.kubernetes.io/master:NoSchedule-
    - kubectl apply -f "https://raw.githubusercontent.com/danderson/metallb/master/manifests/metallb.yaml"

- name: Mark kubeadm as executed
  when: kubeadmex_stat_result.stat.exists == false and master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  copy:
    dest: "{{ ansible_env.HOME }}/.kubeadm"
    content: |
      executed

- name: Install default network_controller
  when: network_controller is not defined and master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  include_role:
    name: network
    tasks_from: flannel
  
- name: Install network_controller
  when: network_controller is defined and master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  include_role:
    name: network
    tasks_from: "{{ network_controller }}"

- name: Wait to raise k8s master
  run_once: true
  when: master_name is defined and master_name.stdout == inventory_hostname
  shell: kubectl get nodes |grep "{{ inventory_hostname }}"|grep Ready
  register: test
  retries: 25
  delay: 10
  until: test.stdout != ""

- name: Install storage_controller
  when: storage is defined and master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  include_role:
    name: storage
    tasks_from: "{{ storage }}"

- name: Define a default external pool for Kubernetes
  when: master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  copy:
    dest: "{{ ansible_env.HOME }}/pool.yml"
    content: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: metallb-system
        name: config
      data:
        config: |
          address-pools:
          - name: my-ip-space
            protocol: layer2
            addresses:
            - {{ network }}.240/28

- name: Create auxiliar system account for administration
  when: master_name is defined and master_name.stdout == inventory_hostname and containerd_stat_result.stat.exists == false
  run_once: true
  shell: "{{ item }}"
  with_items:
    - kubectl create serviceaccount -n kube-system helm-install-sa --dry-run -o yaml | kubectl apply -f -
    - kubectl create clusterrolebinding helm-install-sa --clusterrole=cluster-admin --serviceaccount=kube-system:helm-install-sa --dry-run -o yaml | kubectl apply -f -

- name: Install MetalLB Load Balancer
  when: master_name is defined and master_name.stdout == inventory_hostname and containerd_stat_result.stat.exists == false
  run_once: true
  shell: "{{ item }}"
  with_items:
    - kubectl apply -f "https://raw.githubusercontent.com/danderson/metallb/master/manifests/metallb.yaml"
    - kubectl apply -f {{ ansible_env.HOME }}/pool.yml

- name: Install default ingress
  when: ingress is not defined and master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  include_role:
    name: ingress
    tasks_from: main
  vars:
    ingress_item:
      name: "traefik"
  
- name: Install ingress
  when: ingress is defined and master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  include_role:
    name: ingress
    tasks_from: main
  with_items: "{{ ingress }}"
  loop_control:
    loop_var: ingress_item

- name: Check that initsecret exists
  when: master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  stat:
    path: /tmp/initsecret.yaml
  register: initsecret_stat_result

- name: Create Service Account initnode
  when: initsecret_stat_result.stat.exists == false and master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  shell: "{{ item }}"
  with_items:
    - kubectl create serviceaccount initnode --namespace=kube-system --dry-run -o yaml >>/tmp/initsecret.yaml
    - echo "---" >>/tmp/initsecret.yaml
    - kubectl create clusterrolebinding initauth --serviceaccount=kube-system:initnode --clusterrole=system:node-bootstrapper -n kube-system --dry-run -o yaml >>/tmp/initsecret.yaml
    - kubectl apply -f /tmp/initsecret.yaml

- name: Get secret initnode
  shell: kubectl get serviceaccount -n kube-system initnode -o=jsonpath="{.secrets[0].name}"
  when: master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  register: initnode_secret

- name: Get token initnode
  shell: kubectl get secrets "{{ initnode_secret.stdout }}" -n kube-system -o=jsonpath="{.data.token}"|base64 -d
  when: master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  register: initnode_token

- name: Check that bootstrap-kubeconfig exists
  when: master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  stat:
    path: "{{ ansible_env.HOME }}/bootstrap-kubeconfig"
  register: bootstrap_kubeconfig_stat_result

- name: Create bootstrap-kubeconfig to add new nodes
  when: bootstrap_kubeconfig_stat_result.stat.exists == false and master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  shell: "{{ item }}"
  with_items:
    - kubectl config set-cluster kubernetes --kubeconfig={{ local_home }}/bootstrap-kubeconfig --certificate-authority=/etc/kubernetes/pki/ca.crt --embed-certs --server='https://{{ vm_ip }}:6443'
    - kubectl config set-credentials initnode --kubeconfig={{ local_home }}/bootstrap-kubeconfig --token={{initnode_token.stdout}}
    - kubectl config set-context initnode@kubernetes --cluster=kubernetes --user=initnode --kubeconfig={{ local_home }}/bootstrap-kubeconfig
    - kubectl config use-context initnode@kubernetes --kubeconfig={{ local_home }}/bootstrap-kubeconfig
  vars:
    local_home: "{{ ansible_env.HOME }}"

- name: Load file into variable
  when: master_name is defined and master_name.stdout == inventory_hostname
  slurp:
    src: "{{ local_home }}/bootstrap-kubeconfig"
  register: bootstrap
  run_once: true
  vars:
    local_home: "{{ ansible_env.HOME }}"

- name: Create directory /var/lib/kubelet
  when: master_name is defined and master_name.stdout != inventory_hostname
  file:
    path: /var/lib/kubelet
    state: directory
    mode: '0750'

- name: Check that bootstrap-kubeconfig exists
  when: master_name is defined and master_name.stdout != inventory_hostname
  stat:
    path: "/var/lib/kubelet/bootstrap-kubeconfig"
  register: bootstrap_kubeconfig_stat_result

- copy: 
    content: "{{ bootstrap.content |  b64decode }}"
    dest: /var/lib/kubelet/bootstrap-kubeconfig
  when: master_name is defined and master_name.stdout != inventory_hostname and bootstrap_kubeconfig_stat_result.stat.exists == false

- name: enable and start kubelet service
  when: master_name is defined and master_name.stdout != inventory_hostname
  systemd:
    name: kubelet
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started

- name: Wait to activate kubernetes nodes
  pause:
    seconds: 20

- name: Approve all certificates to activate all the nodes
  shell: kubectl get certificatesigningrequests.certificates.k8s.io |grep ^node-csr|awk '{print $1}'|while read l;do kubectl certificate approve $l;done
  when: master_name is defined and master_name.stdout == inventory_hostname
  run_once: true

- name: Wait to raise kubernetes nodes
  pause:
    seconds: 20

- name: Install addons
  when: addons is defined and master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  include_role:
    name: addons
    tasks_from: main
  with_items: "{{ addons }}"
  loop_control:
    loop_var: addons_item
...
