---
- name: Define a patch for traefik ingress
  when: master_name is defined and master_name.stdout == inventory_hostname and 
  run_once: true
  copy:
    dest: "{{ ansible_env.HOME }}/traefik.weave-scope-app.ingress.patch.yml"
    content: |
      spec:
        rules:
        - host: weave-scope-app.{{ network_name }}.local
          http:
            paths:
            - path: /
              backend:
                serviceName: weave-scope-app
                servicePort: 80

- name: Configure network pool and Dashboard
  when: master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  shell: "{{ item }}"
  with_items:
    - k3s kubectl apply -f "https://cloud.weave.works/k8s/scope.yaml?k8s-version=$(k3s kubectl version | base64 | tr -d '\n')"
    - k3s kubectl patch ingress -n kube-system traefik -p "$(cat {{ ansible_env.HOME }}/traefik.weave-scope-app.ingress.patch.yml)"

- name: Wait to raise k8dash
  shell: k3s kubectl get pods -n kube-system |grep k8dash|grep Running
  register: test
  retries: 25
  delay: 10
  until: test.stdout != ""

- name: Obtain dashboard IP
  shell: k3s kubectl get service -n kube-system k8dashlb -o jsonpath='{.status.loadBalancer.ingress[].ip}'
  register: k8dash_ip

- name: HOW TO ACCESS TO DASHBOARD
  debug:
    msg: |
      Things left to do:
        - Access to https://{{k8dash_ip.stdout}}
        - Use the next token to access dashboard: {{dash_token.stdout}}

...
