---
- name: Wait to raise Traefik
  run_once: true
  shell: k3s kubectl get pods -n kube-system |grep traefik|grep -v helm|grep Running
  register: traefik_state
  retries: 25
  delay: 10
  until: traefik_state.stdout != ""

- name: Define a traefik ingress
  run_once: true
  copy:
    dest: "{{ ansible_env.HOME }}/traefik-ingress.yml"
    content: |
      ---
      apiVersion: extensions/v1beta1
      kind: Ingress
      metadata:
        name: traefik
        namespace: kube-system
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/frontend-entry-points: http,https
          traefik.ingress.kubernetes.io/redirect-entry-point: https
          traefik.ingress.kubernetes.io/redirect-permanent: "true"
      spec:
        rules:
        - host: traefik-ui.{{ network_name }}.local
          http:
            paths:
            - path: /
              backend:
                serviceName: traefik
                servicePort: 8080

- name: Define a patch for traefik configmap
  run_once: true
  copy:
    dest: "{{ ansible_env.HOME }}/traefik.cm.patch.yml"
    content: |
      data:
        traefik.toml: |
          # traefik.toml
          logLevel = "INFO"
          defaultEntryPoints = ["http","https","traefik"]
          [entryPoints]
            [entryPoints.http]
            address = ":80"
            compress = true
            [entryPoints.https]
            address = ":443"
            compress = true
              [entryPoints.https.tls]
                [[entryPoints.https.tls.certificates]]
                CertFile = "/ssl/tls.crt"
                KeyFile = "/ssl/tls.key"
            [entryPoints.traefik]
              address = ":8080"
              [entryPoints.traefik.auth.basic]
              users = ["admin:$apr1$zjjGWKW4$W2JIcu4m26WzOzzESDF0W/"]
          [kubernetes]
            [kubernetes.ingressEndpoint]
            publishedService = "kube-system/traefik"
          [traefikLog]
            format = "json"
          [api]
          entryPoint = "traefik"

- name: Define a patch for traefik deployment
  run_once: true
  copy:
    dest: "{{ ansible_env.HOME }}/traefik.deploy.patch.yml"
    content: |
      spec:
        template:
          spec:
            containers:
            - args:
              - --configfile=/config/traefik.toml
              image: traefik:1.7.9
              name: traefik
              ports:
              - containerPort: 8080
                name: dashboard
                protocol: TCP

- name: Define a patch for traefik service
  run_once: true
  copy:
    dest: "{{ ansible_env.HOME }}/traefik.svc.patch.yml"
    content: |
      spec:
        ports:
        - name: dashboard
          port: 8080
          protocol: TCP
          targetPort: dashboard

- name: Configure traefik deployment
  run_once: true
  shell: k3s kubectl patch deployment -n kube-system traefik -p "$(cat {{ ansible_env.HOME }}/traefik.deploy.patch.yml)"

- name: Configure traefik configmap
  run_once: true
  shell: k3s kubectl patch configmap -n kube-system traefik -p "$(cat {{ ansible_env.HOME }}/traefik.cm.patch.yml)"

- name: Configure traefik service
  run_once: true
  shell: k3s kubectl patch service -n kube-system traefik -p "$(cat {{ ansible_env.HOME }}/traefik.svc.patch.yml)"

- name: Configure traefik ingress
  run_once: true
  shell: k3s kubectl apply -f {{ ansible_env.HOME }}/traefik-ingress.yml
...
