---
- name: Check that network driver is installed
  stat:
    path: "{{ ansible_env.HOME }}/.flannel"
  register: addon_stat_result

- name: Install flannel
  shell: "{{ item }}"
  with_items:
    - kubectl apply -f "https://raw.githubusercontent.com/coreos/flannel/62e44c867a2846fefb68bd5f178daf4da3095ccb/Documentation/kube-flannel.yml"

- name: Mark addon as intalled
  when: addon_stat_result.stat.exists == false
  run_once: true
  copy:
    dest: "{{ ansible_env.HOME }}/.flannel"
    content: |
      installed
...
