---
- name: Check that network driver is installed
  stat:
    path: "{{ ansible_env.HOME }}/.weave"
  register: addon_stat_result

- name: Install weave
  shell: "{{ item }}"
  with_items:
    - kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')&env.NO_MASQ_LOCAL=1"

- name: Wait to raise weave
  shell: kubectl get pods -n kube-system |grep weave-net|grep Running
  register: test
  retries: 25
  delay: 10
  until: test.stdout != ""

- name: Wait to raise coredns
  shell: kubectl get pods -n kube-system |grep coredns|grep Running
  register: test
  retries: 25
  delay: 10
  until: test.stdout != ""

- name: Mark addon as intalled
  when: addon_stat_result.stat.exists == false
  run_once: true
  copy:
    dest: "{{ ansible_env.HOME }}/.weave"
    content: |
      installed
...
