---
- name: stop vm
  virt:
    command: destroy
    name: "{{ inventory_hostname }}"
  ignore_errors: yes

- name: remove DHCP Lease
  shell: |
    virsh net-update {{ network_name }} delete ip-dhcp-host "<host ip='{{ vm_ip }}'/>" --live
  ignore_errors: yes

- name: remove vm
  virt:
    command: undefine
    name: "{{ inventory_hostname }}"
  ignore_errors: yes

- name: remove image
  file:
   path: /var/lib/libvirt/images/{{ inventory_hostname }}.qcow2
   state: absent
...