---
- name: Get all vms
  virt:
    command: list_vms
  register: all_vms
  run_once: true

- name: get networks used by vms
  shell: virsh domiflist --domain {{ item }}|grep network|grep {{ domain.split(".")[0] }}
  with_items: "{{ all_vms.list_vms }} "
  when: interfaces is not defined or interfaces != ""
  run_once: true
  register: interfaces
  ignore_errors: yes

- name: Check if network is used by vms
  debug:
    msg: The network is in use
  register: networkinuse
  run_once: true
  when: item.stdout != ""
  with_items: "{{ interfaces.results }} "

- name: Clear all dhcp leases
  run_once: true
  copy:
    dest: /var/lib/libvirt/dnsmasq/{{ domain.split(".")[0] }}.status
    content: ""

- virt_net:
    command: destroy
    name: "{{ domain.split('.')[0] }}"
  run_once: true
  ignore_errors: yes
  when: networkinuse.results|length == 0

- virt_net:
    command: undefine
    name: "{{ domain.split('.')[0] }}"
  run_once: true
  ignore_errors: yes
  when: networkinuse.results|length == 0
...
