---
- virt:
    command: destroy
    name: "{{ inventory_hostname }}"
  ignore_errors: yes

- name: remove DHCP Lease
  shell: |
    virsh net-update {{ domain.split(".")[0] }} delete ip-dhcp-host "<host ip='{{ vm_ip }}'/>" --live
  ignore_errors: yes

- name: Ansible check if save image exists.
  stat:
    path: "/var/lib/libvirt/qemu/save/{{ inventory_hostname }}.save"
  register: save_file_details

- name: remove save image
  when: save_file_details.stat.exists == true
  file:
   path: "/var/lib/libvirt/qemu/save/{{ inventory_hostname }}.save"
   state: absent

- name: remove vm
  virt:
    command: undefine
    name: "{{ inventory_hostname }}"
  ignore_errors: yes

- name: remove image
  file:
   path: /var/lib/libvirt/images/{{ inventory_hostname }}.qcow2
   state: absent
...