---
- name: Ansible check if image exists.
  stat:
    path: ~/.images/{{ linux_flavor }}.box.tgz
  register: file_details

- name: Download Centos Image
  get_url:
    url: http://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7.Libvirt.box
    dest: ~/.images/centos.box.tgz
    mode: '0440'
  when: file_details.stat.exists == false and linux_flavor == 'centos'
...