---
- name: Ansible check if image exists.
  stat:
    path: "{{ ansible_env.HOME }}/.images/{{ linux_flavor }}.box.tgz"
  register: file_details

- name: Download Oracle Image
  get_url:
    url: https://app.vagrantup.com/generic/boxes/oracle8/versions/1.9.22/providers/libvirt.box
    dest: "{{ ansible_env.HOME }}/.images/oracle.box.tgz"
    mode: '0440'
  when: file_details.stat.exists == false and linux_flavor == 'oracle'

- name: Ansible check if vm image exists.
  stat:
    path: "/var/lib/libvirt/images/{{ inventory_hostname }}.qcow2"
  register: vm_file_details

- name: Ansible check if base image exists.
  stat:
    path: "/var/lib/libvirt/images/box.{{linux_flavor}}.img"
  register: image_details

- name: Unarchive the image
  shell: "tar -zxf {{ ansible_env.HOME }}/.images/{{linux_flavor}}.box.tgz --exclude='./Vagrantfile' --exclude='./metadata.json' -C /var/lib/libvirt/images/"
  when: vm_file_details.stat.exists == false and image_details.stat.exists == false
  args:
    warn: false

- name: rename image
  shell: mv /var/lib/libvirt/images/box.img /var/lib/libvirt/images/box.{{linux_flavor}}.img
  when: vm_file_details.stat.exists == false and image_details.stat.exists == false
...