---
- name: hibernate vm
  shell: virsh save {{ inventory_hostname }} /var/lib/libvirt/qemu/save/{{ inventory_hostname }}.save --running

- name: remove DHCP Lease
  shell: |
    virsh net-update {{ domain.split(".")[0] }} delete ip-dhcp-host "<host ip='{{ vm_ip }}'/>" --live
  ignore_errors: yes
...