---
- name: obtener info de la red
  run_once: true
  virt_net:
    state: active
    name: "{{ domain.split('.')[0] }}"
  register: net_ok
  ignore_errors: yes
  delegate_to: localhost

- include_tasks: create_net.yml
  run_once: true
  when: net_ok.failed == true

- name: Active network
  run_once: true
  virt_net:
    state: active
    name: "{{ domain.split('.')[0] }}"
  delegate_to: localhost

- name: Creates directory
  run_once: true
  file:
    path: ~/.images
    state: directory

- name: include download
  include: "download_{{ linux_flavor }}.yml"
...