---
- name: Helm Powerdns Chart with storage
  vars:
    namespace: "external-dns"
    service: "powerdns"
    file: "https://raw.githubusercontent.com/aescanero/helm-powerdns/master/stable/powerdns.tgz"
    setYaml: |
      {{ lookup('template', 'powerdns.j2') }}
  include_role:
    name: addons
    tasks_from: helm

- name: Load secret token into variable
  shell: kubectl -n external-dns get secret powerdns-secret -o jsonpath='{.data.PDNS_APIKEY}'
  register: token

- name: Call Helm
  vars:
    namespace: "external-dns"
    service: "external-dns"
    file: "stable/external-dns"
    setYaml: |
      provider: "pdns"
      pdns:
        apiUrl: "http://powerdns-service-api.external-dns.svc.{{ domain }}"
        apiPort: 8081
        apiKey: "{{ token.stdout | b64decode }}"
      txtOwnerId: "external-dns"
      domainFilters:
        - "{{ domain }}"
      logLevel: "info"
      interval: "10s"
      rbac:
        create: "true"
  include_role:
    name: addons
    tasks_from: helm

- name: Obtain dashboard IP
  shell: kubectl get service -n external-dns powerdns-service-dns -o jsonpath='{.status.loadBalancer.ingress[].ip}'
  register: externaldns_ip

- name: Make sure old dns conf is not in the resolv.conf configuration
  delegate_to: localhost
  lineinfile:
    path: /etc/resolv.conf
    state: absent
    regexp: '#Added by Ansible External-dns role'

- name: Add a line to resolv.conf
  delegate_to: localhost
  lineinfile:
    path: /etc/resolv.conf
    insertbefore: BOF
    line: 'nameserver {{ externaldns_ip.stdout }} #Added by Ansible External-dns role'
...
