---
#https://hub.kubeapps.com/charts/stable/kube-ops-view
- name: Install kube-ops-view helm with klipper-helm
  copy:
    dest: "{{ ansible_env.HOME }}/kube-ops-view.yml"
    content: |
      ---
      apiVersion: v1
      kind: Namespace
      metadata:
        name: kube-ops-view
      ---
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: helm-install-kube-ops-view
        namespace: kube-system
      spec:
        backoffLimit: 1000
        completions: 1
        parallelism: 1
        template:
          metadata:
            labels:
              jobname: helm-install-kube-ops-view
          spec:
            containers:
            - args:
              - install
              - --namespace
              - kube-ops-view
              - --name
              - kube-ops-view
              - stable/kube-ops-view
              image: rancher/klipper-helm:v0.1.5
              name: helm
            serviceAccount: helm-install-sa
            serviceAccountName: helm-install-sa
            restartPolicy: OnFailure

- name: Configure Service
  shell: kubectl apply -f {{ ansible_env.HOME }}/kube-ops-view.yml

- name: Modify ingress route
  when: addons_item.publish is defined and addons_item.publish['route'] is defined
  include_role:
    name: ingress
    tasks_from: ingress_add_route
  vars:
    service: kube-ops-view-kube-ops-view
    route: "/"
    internalport: 80
    namespace: kube-ops-view
...

