---
- name: Check that addon is installed
  stat:
    path: "{{ ansible_env.HOME }}/.{{ addons_item.name }}"
  register: addon_stat_result

- name: install addon
  when: addon_stat_result.stat.exists == false
  include: "{{ addons_item.name }}.yml"

- name: Mark addon as intalled
  when: addon_stat_result.stat.exists == false
  copy:
    dest: "{{ ansible_env.HOME }}/.{{ addons_item.name }}"
    content: |
      installed
...
