---
- name: Install prometheus-adapter helm
  vars:
    namespace: "prometheus"
    service: "prometheus-adapter"
    file: "stable/prometheus-adapter"
    setYaml: |
      service:
        type: "LoadBalancer"
  include_role:
    name: addons
    tasks_from: helm
...
