---
- name: Check K3s
  when: container_engine == "k3s"
  fail:
    msg: "RIO is ony supported in K3S enviroment"

- name: Deploy RIO
  when: container_engine == "k3s" and master_name is defined and master_name.stdout == inventory_hostname
  run_once: true
  shell: "{{ item }}"
  with_items:
    - curl -sfL https://get.rio.io | sh -
    - rio install
...
