---
- name: Check K3s
  when: container_engine == "k3s"
  fail:
    msg: "RIO is only supported in K3S enviroment"

- name: Deploy RIO
  when: container_engine == "k3s"
  shell: "{{ item }}"
  with_items:
    - curl -sfL https://get.rio.io | sh -
    - rio install
...
