---
- name: Install weave-scope helm
  vars:
    namespace: "weave-scope"
    service: "weave-scope"
    file: "stable/weave-scope "
    setYaml: |
      service:
        type: "LoadBalancer"
  include_role:
    name: addons
    tasks_from: helm

- name: Modify ingress route
  when: addons_item.publish is defined and "route" in addons_item.publish
  include_role:
    name: ingress
    tasks_from: ingress_add_route
  vars:
    service: weave-scope-weave-scope
    route: "/"
    internalport: 80
    namespace: weave-scope
...
