---
- name: Update repositories cache and install dirmngr and curl packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - ebtables
    - ethtool 
    - software-properties-common
    - dirmngr
    - curl
    - socat
    - libseccomp2
  when: ansible_os_family == "Debian"

- name: Update repositories cache and install python3-pip
  apt:
    name: "python3-pip"
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Update repositories cache and install python3-pip
  yum:
    name: "python36-pip"
    state: latest
  when: ansible_os_family == "Redhat"

- name: Install last Docker version
  shell: curl -sSL https://get.docker.com/ | sh
  args:
    warn: no

- name: Install Docker Compose
  shell: "{{ item }}"
  with_items:
    - 'pip3 install docker-compose'

...
