---
- fail:
    msg: "Oracle Linux is not supported"
  when: ansible_distribution == "OracleLinux"

- name: Update repositories cache and install dirmngr and curl packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    force_apt_get: True
  vars:
    packages:
    - ebtables
    - ethtool 
    - software-properties-common
    - dirmngr
    - curl
    - socat
    - libseccomp2
  when: ansible_os_family == "Debian"

- name: Update repositories cache and install python3-pip
  apt:
    name: "python3-pip"
    update_cache: yes
    force_apt_get: True
  when: ansible_os_family == "Debian"

- name: Install last Docker version
  shell: curl -sSL https://get.docker.com/ | sh
  args:
    warn: no

- name: Install Docker Compose from pip
  shell: "{{ item }}"
  with_items:
    - 'pip3 install docker-compose'
  when: ansible_os_family == "Debian"

- name: Update repositories cache and install docker compose
  yum:
    name: "docker-compose"
    state: latest
  when: ansible_os_family == "RedHat"
...
