---
- name: Main Task to Create Virtual Machines
  hosts: vms
  any_errors_fatal: true
  become_user: root
  become: yes
  user: root
  gather_facts: false
  vars_files:
  - vars/os
  - vars/conn
  - vars/virt
  tasks:

  - name: Create network
    import_role:
        name: libvirt
        tasks_from: prepare.yml
    delegate_to: localhost
    connection: local
    when: stat_result is not defined

  - name: Create virtual machine
    import_role:
        name: libvirt
        tasks_from: create.yml
    connection: local
    delegate_to: localhost

  - name: Configure virtual machine
    import_role:
      name: os
      tasks_from: setup.yml
...
