---
- name: Main Task to Create Virtual Machines
  hosts: vms
  any_errors_fatal: true
  become_user: root
  become: yes
  user: root
  gather_facts: false
  vars_files:
  - vars/conn
  - vars/virt
  tasks:
  - name: Remove virtual machine
    import_role:
        name: libvirt
        tasks_from: destroy.yml
    connection: local
    delegate_to: localhost

  - name: Remove Network
    import_role:
        name: libvirt
        tasks_from: destroy_net.yml
    connection: local
    delegate_to: localhost




