all:
  children:
    vms:
      hosts:
        k3s-master:
          memory: 3072
          vcpus: 2
          vm_ip: "192.168.8.10"
          linux_flavor: "debian"
          container_engine: "k3s"
        k3s-node:
          memory: 2048
          vcpus: 2
          vm_ip: "192.168.8.11"
          linux_flavor: "debian"
          container_engine: "k3s"
      vars:
        domain: disasterproject.com
        network: "192.168.8"
        storage: nfs-client
        ingress:
        - traefik
        addons:
        - name: externaldns
          publish:
          - route
          - external
        - name: k8dash
          publish:
          - route
        - name: weave-scope
          publish:
          - route
        - name: dashboard
          publish:
          - route
        - name: kube-ops-view
          publish:
          - route
        - name: kubeview
          publish:
          - route
