all:
  children:
    vms:
      hosts:
        vm1:
          memory: 1024
          vcpus: 1
          vm_ip: "192.168.8.2"
          linux_flavor: "debian"
      vars:
        domain: disasterproject.com
        network: "192.168.8"
