all:
  children:
    vms:
      hosts:
        kubernetes-master:
          memory: 2048
          vcpus: 2
          vm_ip: "192.168.8.2"
          linux_flavor: "debian"
          container_engine: "kubernetes"
        kubernetes-node:
          memory: 1024
          vcpus: 1
          vm_ip: "192.168.8.3"
          linux_flavor: "debian"
          container_engine: "kubernetes"
      vars:
        domain: disasterproject.com
        network: "192.168.8"
        network_controller: weave
        storage: nfs-client
        ingress:
        - traefik
        addons:
        - name: externaldns
          storage: nfs
          publish:
          - route
          - external
        - name: weave-scope
          publish:
          - route



